name: Marten NuGet Manual Publish

on: [workflow_dispatch]

env:
  config: Release
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  dotnet_core_version: 5.0.100
  # GitHub Packages Feed settings
  GITHUB_FEED: https://nuget.pkg.github.com/clinia/index.json
  GITHUB_USER: clinia-ci
  GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}

jobs:
  publish_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.dotnet_core_version }}

      - name: Run Pack
        run: ./build.sh --no-color pack
        shell: bash

      - name: Publish to NuGet
        run: |
          find . -name '*.nupkg' -exec dotnet nuget push "{}" -s $GITHUB_FEED -k ${{ secrets.GHCR_TOKEN }} \;
          # find . -name '*.snupkg' -exec dotnet nuget push "{}" -s $GITHUB_FEED -k ${{ secrets.GHCR_TOKEN }} \;
        shell: bash
